import {manageTeams,githubStore} from './teams.mjs';
import teamCatalog from '../functions/team-catalog.js';
import custom from '../functions/custom-notifications.js';
import {accessToken,firebase,Timestamp} from './firebase-rest.mjs';
const ADMIN='ZJeZEjtDeMRCYL0UOuvhGt0gNCT2',EMAIL='juanjocarrillo7@gmail.com',REPO='djyuanyo/CDMenciana';
const ORIGINS=['https://appassets.androidplatform.net','https://cdmenciana.web.app','https://cdmenciana.firebaseapp.com'];
const error=(message,status=400)=>Object.assign(Error(message),{status});
const json=(value,status=200,origin)=>new Response(JSON.stringify(value),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store',...(ORIGINS.includes(origin)?{'Access-Control-Allow-Origin':origin,'Vary':'Origin'}:{})}});
async function body(request,max=500000){if(Number(request.headers.get('content-length'))>max)throw error('La imagen es demasiado grande.',413);const reader=request.body?.getReader();if(!reader)throw error('Faltan los datos.');let size=0,chunks=[];while(true){const {done,value}=await reader.read();if(done)break;size+=value.length;if(size>max){await reader.cancel();throw error('La imagen es demasiado grande.',413);}chunks.push(value);}const bytes=new Uint8Array(size);let at=0;for(const c of chunks){bytes.set(c,at);at+=c.length;}try{return JSON.parse(new TextDecoder().decode(bytes));}catch{throw error('Datos no válidos.');}}
export function validateNotice(v,now=Date.now(),teams=teamCatalog.BASE){
 if(!/^[a-f0-9]{32}$/.test(v.id||'')||typeof v.title!=='string'||!v.title.trim()||v.title.length>100||typeof v.body!=='string'||!v.body.trim()||v.body.length>500||!(v.teamKey==='all'||Object.hasOwn(teams,v.teamKey))||!['now','scheduled'].includes(v.mode)||!custom.validImage(v.imageUrl||''))throw error('Revisa el título, mensaje y destinatarios.');
 if(v.mode==='scheduled'&&(!Number.isFinite(v.scheduledAt)||v.scheduledAt<=now||v.scheduledAt>now+30*86400000))throw error('Elige una fecha y hora futura, hasta 30 días desde ahora.');
 return {title:v.title.trim(),body:v.body.trim(),teamKey:v.teamKey,mode:v.mode,imageUrl:v.imageUrl||'',scheduledAt:Timestamp.fromMillis(v.mode==='scheduled'?v.scheduledAt:now),createdAt:Timestamp.fromMillis(now),createdBy:ADMIN,status:v.mode==='scheduled'?'scheduled':'sending'};
}
async function audiences(key,service){if(key==='all'||Object.hasOwn(teamCatalog.BASE,key))return teamCatalog.BASE;if(!teamCatalog.validKey(key))throw error('Equipo no disponible.');const saved=await service.db.collection('clubTeams').doc(key).get(),t=saved.data();if(!saved.exists||t.status!=='active'||!/^\d{1,12}$/.test(t.teamId||''))throw error('Equipo no disponible.');return {...teamCatalog.BASE,[key]:t.teamId};}
async function internalKey(env){const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode('club-internal|'+env.FIREBASE_SERVICE_ACCOUNT));return Array.from(new Uint8Array(bytes),n=>n.toString(16).padStart(2,'0')).join('');}
export async function manageScheduled(id,input,service,cancel=false,now=Date.now(),teams=teamCatalog.BASE){
 if(!/^[a-f0-9]{32}$/.test(id)||!Number.isSafeInteger(input.revision)||input.revision<0)throw error('Aviso no válido.');
 if(!cancel&&!/^[a-f0-9]{32}$/.test(input.mutationId||''))throw error('Cambio no válido.');
 const ref=service.db.collection('clubNotificationRequests').doc(id),pointer=service.db.collection('clubNotificationSchedule').doc(id);let result;
 const edit=cancel?null:validateNotice({...input,id,mode:'scheduled'},now,teams);
 await service.db.runTransaction(async tx=>{
  const snapshot=await tx.get(ref);if(!snapshot.exists)throw error('El aviso no existe.',404);const v=snapshot.data();
  if(cancel&&v.status==='cancelled'){result={id,status:'cancelled'};return;}
  if(!cancel&&v.lastEditId===input.mutationId&&v.revision===input.revision+1){if(['title','body','teamKey','imageUrl'].some(key=>v[key]!==edit[key])||v.scheduledAt.toMillis()!==edit.scheduledAt.toMillis())throw error('El cambio ya existe con otro contenido.',409);result={id,status:v.status,acceptedCount:v.acceptedCount||0,scheduledAt:v.scheduledAt.toMillis(),revision:v.revision};return;}
  if(v.createdBy!==ADMIN||v.status!=='scheduled'||v.mode!=='scheduled')throw error('El aviso ya ha empezado a enviarse o no está programado. Actualiza el historial.',409);
  if((v.revision||0)!==input.revision)throw error('El aviso ha cambiado. Actualiza el historial antes de editarlo.',409);
  if(cancel){tx.set(ref,{...v,status:'cancelled',revision:input.revision+1,cancelledAt:Timestamp.fromMillis(now)});tx.delete(pointer);result={id,status:'cancelled'};}
  else{tx.set(ref,{...v,...edit,createdAt:v.createdAt,revision:input.revision+1,lastEditId:input.mutationId,updatedAt:Timestamp.fromMillis(now)});tx.set(pointer,{dueAt:edit.scheduledAt.toMillis()});result={id,status:'scheduled',scheduledAt:edit.scheduledAt.toMillis(),revision:input.revision+1};}
 });return result;
}
async function administrator(request,env,service){const token=request.headers.get('Authorization')?.replace(/^Bearer /,'');if(!token)throw error('Inicia sesión.',401);const r=await fetch('https://identitytoolkit.googleapis.com/v1/accounts:lookup?key='+env.FIREBASE_API_KEY,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({idToken:token})});if(!r.ok)throw error('Vuelve a iniciar sesión.',401);const u=(await r.json()).users?.[0];if(u?.validSince){try{const claims=JSON.parse(atob(token.split('.')[1].replace(/-/g,'+').replace(/_/g,'/')));if(Number(u.validSince)>claims.iat)throw error('Vuelve a iniciar sesión.',401);}catch(e){throw error('Vuelve a iniciar sesión.',401);}}if(u?.localId!==ADMIN||u.email?.toLowerCase()!==EMAIL||u.disabled)throw error('Solo el administrador puede enviar avisos.',403);const [owner,marker]=await Promise.all([service.auth.getUser(ADMIN),service.db.collection('clubDeletedAccounts').doc(ADMIN).get()]);if(owner.disabled||owner.email?.toLowerCase()!==EMAIL||marker.exists)throw error('Cuenta administradora no disponible.',403);return token;}
export async function dispatch(id,env,service){
 const ref=service.db.collection('clubNotificationRequests').doc(id),snapshot=await ref.get();let v=snapshot.data();if(!snapshot.exists)throw error('El aviso no existe.',404);if(['sent','cancelled'].includes(v.status)){await service.db.collection('clubNotificationSchedule').doc(id).delete();return {status:v.status,acceptedCount:v.acceptedCount||0};}if(v.status==='invalid')throw error('El aviso no es válido.');if(v.scheduledAt?.toMillis()>Date.now())return {status:'scheduled',scheduledAt:v.scheduledAt.toMillis()};
 const teams=await audiences(v.teamKey,service);if(!custom.validRequest(v,teams))throw error('El aviso no es válido.');if(!env.DELIVERY)throw error('El servicio de envío no está configurado.',503);
 // Claim the whole notice atomically before sending; edits/cancellation use the same document.
 let stopped;
 await service.db.runTransaction(async tx=>{stopped=undefined;const current=await tx.get(ref);v=current.data();if(['sent','cancelled'].includes(v.status)){stopped={status:v.status,acceptedCount:v.acceptedCount||0};return;}if(v.scheduledAt?.toMillis()>Date.now()){stopped={status:'scheduled',scheduledAt:v.scheduledAt.toMillis()};return;}if(!custom.validRequest(v,teams))throw error('El aviso no es válido.');tx.set(ref,{...v,status:'sending'});});
 if(stopped)return stopped;
 const snapshotDevices=await service.db.collectionGroup('devices').get(),devices={docs:snapshotDevices.docs.filter(d=>/^clubUsers\/[A-Za-z0-9_-]+\/devices\/[a-f0-9]{64}$/.test(d.ref.path))},key=await internalKey(env);let acceptedCount=0,retry=false;
 // Each private invocation handles three phones, remaining below Workers Free's 50 subrequests.
 for(let at=0;at<devices.docs.length;at+=3){const r=await env.DELIVERY.fetch(new Request('https://club.internal/batch',{method:'POST',headers:{'X-Club-Internal':key,'Content-Type':'application/json'},body:JSON.stringify({id,paths:devices.docs.slice(at,at+3).map(d=>d.ref.path)})}));if(!r.ok){retry=true;continue;}const result=await r.json();acceptedCount+=result.accepted;retry ||= result.retry;}
 await service.db.runTransaction(async tx=>{const current=await tx.get(ref);if(current.data().status==='sent'){acceptedCount=current.data().acceptedCount||0;retry=false;return;}tx.set(ref,{...current.data(),status:retry?'sending':'sent',acceptedCount,processedAt:Timestamp.fromMillis(Date.now())});});const pointer=service.db.collection('clubNotificationSchedule').doc(id);if(retry)await pointer.set({dueAt:Date.now()+60000});else await pointer.delete();return {status:retry?'retry':'sent',acceptedCount};
}
export async function uploadImage(v,env,fetcher=fetch){
 if(!/^[a-f0-9]{32}$/.test(v.id||'')||typeof v.base64!=='string'||v.base64.length>410000||!/^[A-Za-z0-9+/]+={0,2}$/.test(v.base64))throw error('Selecciona una imagen JPG de hasta 300 KB.');const bytes=atob(v.base64);if(bytes.length>300000||bytes.charCodeAt(0)!==255||bytes.charCodeAt(1)!==216||bytes.charCodeAt(2)!==255)throw error('La imagen no es un JPG válido.');if(!env.GITHUB_IMAGE_TOKEN)throw error('La subida de imágenes todavía no está activada.',503);
 const path=`notification-images/${v.id}.jpg`,url=`https://api.github.com/repos/${REPO}/contents/${path}`,headers={Authorization:'Bearer '+env.GITHUB_IMAGE_TOKEN,'Accept':'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28','User-Agent':'CDMenciana-avisos','Content-Type':'application/json'};
 let r=await fetcher(url,{method:'PUT',headers,body:JSON.stringify({message:'media: image for club notification',content:v.base64,branch:'main'})});if(!r.ok){if(r.status===422){const existing=await fetcher(url+'?ref=main',{headers});const data=existing.ok?await existing.json():{};if(data.content?.replace(/\s/g,'')===v.base64)return {imageUrl:`https://raw.githubusercontent.com/${REPO}/main/${path}`};}throw error('No se pudo guardar la imagen en GitHub.',502);}return {imageUrl:`https://raw.githubusercontent.com/${REPO}/main/${path}`};
}
export async function handle(request,env){const origin=request.headers.get('Origin'),path=new URL(request.url).pathname;try{
 if(request.method==='OPTIONS')return new Response(null,{status:ORIGINS.includes(origin)?204:403,headers:{'Access-Control-Allow-Origin':ORIGINS.includes(origin)?origin:'','Access-Control-Allow-Methods':'POST, GET, OPTIONS','Access-Control-Allow-Headers':'Authorization, Content-Type','Vary':'Origin'}});
 if(path==='/health'&&request.method==='GET')return json({ready:!!env.FIREBASE_SERVICE_ACCOUNT&&!!env.DELIVERY,images:!!env.GITHUB_IMAGE_TOKEN,scheduledManagement:true},200,origin);
 if(path==='/connection'&&request.method==='POST'){if(request.headers.get('X-Club-Internal')!==await internalKey(env))throw error('No autorizado.',403);const service=firebase(env,await accessToken(env)),owner=await service.auth.getUser(ADMIN);if(owner.disabled||owner.email?.toLowerCase()!==EMAIL)throw error('Cuenta administradora no disponible.',503);await service.db.collection('clubNotificationConfig').doc('status').get();const r=await fetch('https://api.github.com/repos/'+REPO,{headers:{Authorization:'Bearer '+env.GITHUB_IMAGE_TOKEN,'Accept':'application/vnd.github+json','User-Agent':'CDMenciana-avisos'}});if(!r.ok)throw error('La conexión con GitHub no está disponible.',503);return json({ready:!!env.DELIVERY,images:true});}
 if(path==='/batch'&&request.method==='POST'){if(request.headers.get('X-Club-Internal')!==await internalKey(env))throw error('No autorizado.',403);const input=await body(request,5000);if(!/^[a-f0-9]{32}$/.test(input.id||'')||!Array.isArray(input.paths)||input.paths.length>3||input.paths.some(p=>!/^clubUsers\/[A-Za-z0-9_-]+\/devices\/[a-f0-9]{64}$/.test(p)))throw error('Lote inválido.');const service=firebase(env,await accessToken(env)),deviceDocs=await Promise.all(input.paths.map(p=>{const parts=p.split('/');return service.db.collection('clubUsers').doc(parts[1]).collection('devices').doc(parts[3]).get();}));return json(await custom.processCustom({...service,requestId:input.id,deviceDocs,finalize:false}));}
 if(origin&&!ORIGINS.includes(origin))throw error('Origen no permitido.',403);const service=firebase(env,await accessToken(env));await administrator(request,env,service);
 if(['/teams','/teams/preview','/teams/import','/teams/update'].includes(path)&&request.method==='POST')return json(await manageTeams(path,await body(request,5000),githubStore(env)),200,origin);
 if(path==='/images'&&request.method==='POST')return json(await uploadImage(await body(request),env),200,origin);
 if(/^\/messages\/[a-f0-9]{32}\/(edit|cancel)$/.test(path)&&request.method==='POST'){const [, ,id,action]=path.split('/');const input=await body(request,5000),teams=action==='cancel'?teamCatalog.BASE:await audiences(input.teamKey,service);return json(await manageScheduled(id,input,service,action==='cancel',Date.now(),teams),200,origin);}
 if(path==='/messages'&&request.method==='POST'){
  const input=await body(request,5000);if(!/^[a-f0-9]{32}$/.test(input.id||''))throw error('Aviso no válido.');const ref=service.db.collection('clubNotificationRequests').doc(input.id),previous=await ref.get(),data=validateNotice(input,previous.exists?previous.data().createdAt.toMillis():Date.now(),await audiences(input.teamKey,service));
  if(previous.exists){const p=previous.data();if(p.status==='cancelled')throw error('Este aviso se ha eliminado. Crea uno nuevo.',409);if(['title','body','teamKey','mode','imageUrl'].some(k=>p[k]!==data[k])||(data.mode==='scheduled'&&p.scheduledAt.toMillis()!==data.scheduledAt.toMillis()))throw error('El aviso ya existe con otro contenido.',409);}else{try{await service.create('clubNotificationRequests/'+input.id,data);}catch(e){if(![409,412].includes(e.status))throw e;throw error('El aviso está procesándose. Pulsa Reintentar.',409);}}
  if(!previous.exists||previous.data().status!=='sent')await service.db.collection('clubNotificationSchedule').doc(input.id).set({dueAt:data.scheduledAt.toMillis()});
  return json({id:input.id,...(input.mode==='scheduled'?{status:'scheduled',scheduledAt:data.scheduledAt.toMillis()}:await dispatch(input.id,env,service))},200,origin);
 }
 if(/^\/messages\/[a-f0-9]{32}\/retry$/.test(path)&&request.method==='POST'){const id=path.split('/')[2];return json({id,...await dispatch(id,env,service)},200,origin);}
 throw error('Ruta no disponible.',404);
 }catch(e){return json({error:e.status?e.message:'No se pudo completar el envío. Puedes reintentarlo.'},e.status||503,origin);}}
export default {fetch:handle,async scheduled(event,env,ctx){ctx.waitUntil((async()=>{const service=firebase(env,await accessToken(env)),due=await service.db.collection('clubNotificationSchedule').where('dueAt','<=',Date.now()).limit(5).get();for(const d of due.docs){try{await dispatch(d.id,env,service);}catch{await d.ref.update({dueAt:Date.now()+60000});}}})());}};

