#!/usr/bin/env python3
"""Bundle club modules into an asset supported by existing native shells."""
from pathlib import Path
import json

root = Path(__file__).resolve().parents[1]
modules = ('club-access.js', 'registration.js', 'account-delete.js', 'favorites.js', 'notifications.js', 'teams.js', 'families.js')
source = root / 'server/static'
target = root / 'android/app/src/main/assets/club-access.js'
target.write_text('/* Generated by tools/bundle_account_assets.py; edit server/static modules. */\n' +
                  '\n'.join((source / name).read_text() for name in modules))
(root / 'notification-service/legal-pages.mjs').write_text('/* Generated from the public policies. */\nexport default '+json.dumps({name:(source/name).read_text() for name in ('privacy.html','delete-account.html')},ensure_ascii=False)+';\n')
