const assert=require('node:assert/strict'),fs=require('node:fs'),{JSDOM}=require('jsdom');
async function setup(){
 const dom=new JSDOM('<main></main>',{url:'https://cdmenciana.web.app/',runScripts:'outside-only'}),W=dom.window;
 W.CDM={icon:()=>'',confirm:async()=>true,empty:()=>''};W.AbortController=AbortController;
 for(const name of ['auth','registration','club-access','account-delete'])W.eval(fs.readFileSync('server/static/'+name+'.js','utf8'));
 W.ClubAuth.firebase=()=>true;W.ClubAuth.configured=true;W.ClubAuth.user={uid:'player',name:'Player',email:'player@club.test',emailVerified:true};
 W.ClubAccess.profile={id:'player',name:'Player',role:'fan',registrationType:'fan',registrationComplete:'true'};
 const token='a.'+Buffer.from(JSON.stringify({auth_time:Math.floor(Date.now()/1000)})).toString('base64url')+'.c',calls=[];
 W.ClubAuth.request=async action=>{calls.push(action);if(action==='logout'){W.ClubAuth.update({user:null});return {};}return {token,user:W.ClubAuth.user};};
 W.fetch=async(url,options)=>{calls.push(url);return {ok:true,status:200,json:async()=>url.includes('clubDeletedAccounts')?{fields:{}}:url.includes('cloudfunctions')?{result:{deleted:true}}:{}};};
 return {dom,W,calls};
}
(async()=>{
 let s=await setup();s.W.CDM.confirm=async()=>false;await s.W.ClubDeletion.own();assert.deepEqual(s.calls,[]);s.dom.window.close();
 s=await setup();assert(s.W.ClubAuth.screen(s.W.ClubAccess.user()).includes('Eliminar mi cuenta'));await s.W.ClubDeletion.own();assert.equal(s.W.ClubAuth.user,null);assert(s.W.ClubAuth.message.includes('se ha eliminado'));assert(s.calls.findIndex(x=>x.includes(':commit'))<s.calls.findIndex(x=>x.includes('accounts:delete')));s.dom.window.close();
 s=await setup();s.W.ClubAuth.request=async()=>({token:'a.'+Buffer.from(JSON.stringify({auth_time:1})).toString('base64url')+'.c',user:s.W.ClubAuth.user});await s.W.ClubDeletion.own();assert.equal(s.calls.length,0);assert(s.W.ClubAuth.error);assert(s.W.ClubAuth.message.includes('cierra sesión'));s.dom.window.close();
 s=await setup();let payload;s.W.fetch=async(url,options)=>{payload=options.body&&JSON.parse(options.body);s.calls.push(url);if(url.includes('accounts:delete'))throw Error('offline');return {ok:true,status:200,json:async()=>({})};};await s.W.ClubDeletion.own();assert(s.W.ClubDeletion.pending);assert.equal(s.W.ClubAccess.profile,null);assert(s.W.ClubAuth.screen().includes('Eliminación pendiente'));assert.equal(s.W.ClubAuth.user.uid,'player');s.dom.window.close();
 s=await setup();s.W.fetch=async url=>({ok:false,status:403,json:async()=>({error:{message:'Denied'}})});await s.W.ClubDeletion.own();assert(s.W.ClubAccess.profile);assert(!s.W.ClubDeletion.pending);assert(s.W.ClubAuth.user);s.dom.window.close();
 s=await setup();await assert.rejects(s.W.ClubDeletion.admin('player'),/administrador/);s.W.ClubAuth.user={uid:'ZJeZEjtDeMRCYL0UOuvhGt0gNCT2',email:'juanjocarrillo7@gmail.com',emailVerified:true};s.W.ClubAccess.users=[{id:'player',name:'Player',email:'player@club.test'}];assert(s.W.ClubAccess.rows().includes('data-delete-user'));await s.W.ClubDeletion.admin('player');assert.equal(s.W.ClubAccess.users.length,0);await assert.rejects(s.W.ClubDeletion.admin('ZJeZEjtDeMRCYL0UOuvhGt0gNCT2'),/otra cuenta/);s.dom.window.close();
 s=await setup();s.W.ClubAuth.user={uid:'ZJeZEjtDeMRCYL0UOuvhGt0gNCT2',email:'juanjocarrillo7@gmail.com',emailVerified:true};s.W.ClubAccess.users=[{id:'player',name:'Player',email:'player@club.test'},{id:'ZJeZEjtDeMRCYL0UOuvhGt0gNCT2',name:'Owner',email:'juanjocarrillo7@gmail.com'}];s.W.document.body.innerHTML='<div id="club-users">'+s.W.ClubAccess.rows()+'</div>';assert.equal(s.W.document.querySelectorAll('[data-delete-user]').length,1);
 s.W.CDM.confirm=async()=>false;s.W.document.querySelector('[data-delete-user]').click();await new Promise(r=>setTimeout(r,0));assert(!s.calls.some(x=>x.includes('cloudfunctions')));
 s.W.CDM.confirm=async()=>true;s.W.fetch=async()=>({ok:false,status:404,json:async()=>({})});s.W.document.querySelector('[data-delete-user]').click();await new Promise(r=>setTimeout(r,10));assert(s.W.document.querySelector('.role-feedback').textContent.includes('todavía no está activado'));assert.equal(s.W.ClubAccess.users.length,2);assert(s.W.document.querySelector('[data-delete-user]'));s.dom.window.close();
 s=await setup();let cleanupWrites; s.W.ClubFavorites={detach:async()=>s.calls.push('detach')};s.W.ClubAccess.request=async p=>({documents:[{name:'projects/barpro-pos-menciana/databases/(default)/documents/clubUsers/player/'+(p.includes('/favorites')?'favorites/first_123':'devices/device')}]});s.W.fetch=async(url,options)=>{if(url.includes(':commit'))cleanupWrites=JSON.parse(options.body).writes;return {ok:true,status:200,json:async()=>({})};};await s.W.ClubDeletion.own();assert.equal(cleanupWrites.length,4);assert(cleanupWrites.some(w=>w.delete?.includes('/favorites/')));assert(cleanupWrites.some(w=>w.delete?.includes('/devices/')));assert(s.calls.includes('detach'));s.dom.window.close();
 console.log('Account deletion: confirmation, fresh login, atomic cleanup, pending retry, Google-safe copy and administrator boundaries passed.');
})().catch(e=>{console.error(e);process.exitCode=1;});
