import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {calendarSource,manageTeams,githubStore} from '../notification-service/teams.mjs';import {validateNotice} from '../notification-service/worker.mjs';import catalog from '../functions/team-catalog.js';import custom from '../functions/custom-notifications.js';
const initial={version:1,teams:['first','filial','infantil'].map((key,index)=>({...JSON.parse(fs.readFileSync('data/club-teams.json')).teams.find(t=>t.key===key),order:index+1}))},id='a'.repeat(32),source='https://www.rfaf.es/pnfg/NPcd/NFG_VisCalendario_Vis?codtemporada=22&codcompeticion=49465203&codgrupo=49465413&CodJornada=3';
function mock(){const rows=new Map([['data/club-teams.json',{sha:'revision1',value:structuredClone(initial)}]]);return {rows,read:async p=>structuredClone(rows.get(p)||null),write:async(p,value,sha)=>{assert.equal(sha,rows.get(p)?.sha);rows.set(p,{sha:(sha||'')+'x',value:structuredClone(value)});}};}
test('RFAF links are normalized; SSRF, ambiguous parameters and missing identities rejected',()=>{assert.equal(calendarSource(source),source.replace('?codtemporada','?cod_primaria=1000120&codtemporada'));for(const v of ['http://www.rfaf.es/a','https://evil.test/'+source,'https://www.rfaf.es@evil.test/calendar','https://www.rfaf.es:444/pnfg/NPcd/NFG_VisCalendario_Vis','https://www.rfaf.es/pnfg/NPcd/NFG_VisCalendario_Vis?codgrupo=1&CodGrupo=2'])assert.throws(()=>calendarSource(v));});
test('Preview jobs are idempotent; import accepts only verified club candidates and no duplicate teams',async()=>{const store=mock();await manageTeams('/teams/preview',{id,source},store);const first=store.rows.get('data/team-imports/'+id+'.json');await manageTeams('/teams/preview',{id,source},store);assert.equal(store.rows.get('data/team-imports/'+id+'.json').sha,first.sha);await assert.rejects(manageTeams('/teams/import',{id,teamId:'999',label:'Rival',order:4},store));store.rows.get('data/team-imports/'+id+'.json').value={id,source,status:'preview_ready',preview:{group_id:'49465413',season_id:'22',candidates:[{team_id:'1234',team_name:'C.D. MENCIANA'}]}};await assert.rejects(manageTeams('/teams/import',{id,teamId:'999',label:'Rival',order:4},store));const result=await manageTeams('/teams/import',{id,teamId:'1234',label:'Cadete',order:4},store);assert.equal(result.job.status,'import_pending');const repeated=await manageTeams('/teams/import',{id,teamId:'1234',label:'Cadete',order:4},store);assert.equal(repeated.job.selectedTeam,'1234');assert.equal(store.rows.get('data/club-teams.json').value.teams.length,3);});
test('Renaming/reordering retains keys, fixture names and favorites; stale edits cannot clobber changes',async()=>{const store=mock(),result=await manageTeams('/teams/update',{key:'infantil',label:'Infantil A',order:1,revision:'revision1'},store);assert.equal(result.teams[0].key,'infantil');assert.equal(result.teams[0].team_id,'34369965');assert.deepEqual(result.teams.map(t=>t.order),[1,2,3]);await assert.rejects(manageTeams('/teams/update',{key:'first',label:'Uno',order:1,revision:'revision1'},store),e=>e.status===409);});
test('Dynamic audiences require a trusted configured identity; malformed keys and rival ids are rejected',()=>{const teams={...catalog.BASE,rfaf_49465413_1234:'1234'},v={id,title:'Aviso',body:'Mensaje',teamKey:'rfaf_49465413_1234',mode:'now'};assert.throws(()=>validateNotice(v));assert.equal(validateNotice(v,1000,teams).teamKey,v.teamKey);const notice=validateNotice(v,1000,teams);assert(custom.validRequest(notice,teams));assert(custom.subscribed(notice,[{teamKey:v.teamKey,teamId:'1234'}],teams));assert(!custom.subscribed(notice,[{teamKey:v.teamKey,teamId:'999'}],teams));assert(!catalog.validKey('../../secret'));});
test('GitHub transport uses CAS and UTF-8 without credentials in public content',async()=>{const calls=[],store=githubStore({GITHUB_IMAGE_TOKEN:'private'},async(u,o)=>{calls.push([u,o]);return Response.json({});});await store.write('data/team-imports/'+id+'.json',{label:'Infantil Ñ'},'known');const body=JSON.parse(calls[0][1].body);assert.equal(body.sha,'known');assert.equal(new TextDecoder().decode(Uint8Array.from(atob(body.content),c=>c.charCodeAt(0))),'{\n  "label": "Infantil Ñ"\n}\n');assert(!JSON.stringify(body).includes('private'));});
test('Deleting an added team retires it, preserves original favorites and rejects stale deletion',async()=>{
 const store=mock(),extra={...initial.teams[2],key:'rfaf_49520774_1234',team_id:'1234',filename:'fixtures-rfaf_49520774_1234.json',label:'Prueba',order:4};
 store.rows.get('data/club-teams.json').value.teams.push(extra);
 await assert.rejects(manageTeams('/teams/delete',{key:extra.key,revision:'stale'},store),e=>e.status===409);
 await assert.rejects(manageTeams('/teams/delete',{key:'first',revision:'revision1'},store));
 const result=await manageTeams('/teams/delete',{key:extra.key,revision:'revision1'},store);
 assert.deepEqual(result.teams.map(t=>t.key),['first','filial','infantil']);
 assert.deepEqual(store.rows.get('data/club-teams.json').value.retired,[extra.key]);
 await manageTeams('/teams/update',{key:'first',label:'Primer Equipo',order:1,revision:'revision1x'},store);
 assert.deepEqual(store.rows.get('data/club-teams.json').value.retired,[extra.key]);
});
