const assert=require('node:assert/strict'),fs=require('node:fs'),{JSDOM}=require('jsdom');
(async()=>{
 const dom=new JSDOM('<main></main>',{url:'https://cdmenciana.web.app/',runScripts:'outside-only'}),W=dom.window;
 W.CDM={icon:()=>'',empty:(a,b)=>a+b};W.AbortController=AbortController;
 for(const file of ['auth','club-access','account-delete','notifications','teams','review-demo'])W.eval(fs.readFileSync(`server/static/${file}.js`,'utf8'));
 const script=fs.readFileSync('server/static/review-demo.js','utf8'),uid=JSON.parse(script.match(/reviewUid=("[^"]+")/)[1]),email=JSON.parse(script.match(/reviewEmail=("[^"]+")/)[1]);
 const access=W.ClubAccess,teams=W.ClubTeams,notifications=W.ClubNotifications;
 W.Fixtures={teams:{first:{label:'Primer Equipo'}},selectedTeam:'first'};
 let requests=0;W.fetch=async()=>{requests++;throw Error('Unexpected production request');};
 W.ClubAuth.user={uid,email};W.dispatchEvent(new W.CustomEvent('club-auth-state'));
 assert(access.administrator());assert(access.screen().includes('datos ficticios'));
 await access.list();assert.equal(access.users.length,2);await access.setRole('demo-member','member_player');assert.equal(access.users[0].role,'member_player');
 await assert.rejects(access.setRole('production-user','player'));await assert.rejects(access.setRole('demo-player','admin'));await assert.rejects(async()=>access.request('?pageSize=300'));
 await W.ClubDeletion.admin('demo-player');assert.equal(access.users.length,1);await assert.rejects(W.ClubDeletion.admin(uid));
 const fixturesBefore=JSON.stringify(W.Fixtures),storageBefore=W.localStorage.length;
 await teams.preview('https://www.rfaf.es/pnfg/NPcd/NFG_VisCalendario_Vis?codgrupo=1');await teams.add({teamId:'1005',label:'Categoría ficticia',order:5});assert(teams.rows.some(t=>t.label==='Categoría ficticia'));
 await teams.http('/teams/update',{key:'rfaf_9000_9002',label:'Renombrado',order:4});await teams.refresh();assert(teams.rows.some(t=>t.label==='Renombrado'));
 await teams.remove('rfaf_9000_9002');assert(!teams.rows.some(t=>t.key==='rfaf_9000_9002'));assert.equal(JSON.stringify(W.Fixtures),fixturesBefore);assert.equal(W.localStorage.length,storageBefore);
 const now=await notifications.queue({title:'Aviso de prueba',body:'Ficticio',teamKey:'all',mode:'now'});assert.equal(now.status,'sent');assert.equal(now.acceptedCount,0);assert(notifications.message(now).includes('simulado'));
 const scheduled=await notifications.queue({title:'Programado',body:'Ficticio',teamKey:'first',mode:'scheduled',scheduledAt:new Date(Date.now()+3600000).toISOString()});
 W.document.querySelector('main').innerHTML=access.screen('history');await notifications.history();assert(W.document.querySelector('[data-notification-edit]'));assert(notifications.historyRows.has(scheduled.id));
 await notifications.edit(scheduled.id,{title:'Modificado',body:'Prueba',teamKey:'all',scheduledAt:new Date(Date.now()+7200000).toISOString(),revision:1});assert.equal(W.ClubReviewDemo.messages.get(scheduled.id).title,'Modificado');
 await notifications.http('/messages/'+scheduled.id+'/cancel',{revision:2});assert.equal(W.ClubReviewDemo.messages.get(scheduled.id).status,'cancelled');
 const image=await notifications.http('/images',{base64:'ZmFrZQ=='});assert(image.imageUrl.startsWith('data:'));assert.equal(requests,0);
 W.ClubAuth.user={uid:'wrong',email};assert(!access.administrator(),'An email alone never opens the sandbox');
 W.ClubAuth.user={uid,email:'wrong@example.test'};assert(!access.administrator(),'A UID alone never opens the sandbox');
 W.ClubAuth.user=null;W.dispatchEvent(new W.CustomEvent('club-auth-state'));assert.equal(access.users.length,0);assert.equal(notifications.historyRows.size,0);assert.equal(W.ClubReviewDemo.messages.size,0);await assert.rejects(notifications.http('/messages',{}));
 W.ClubAuth.user={uid:access.adminUid,email:access.adminEmail};W.ClubAuth.request=async()=>({token:'test-token',user:W.ClubAuth.user});assert(access.administrator());
 W.fetch=async()=>{requests++;return {ok:true,json:async()=>({documents:[]})};};await access.list();assert.equal(requests,1,'Real administrator still uses the production transport');
 assert(!fs.readFileSync('firestore.rules','utf8').includes(uid),'No backend administrator rights added');
 dom.window.close();console.log('Review sandbox: no production requests, synthetic CRUD, role safety, scheduling, image isolation, identity gate and sign-out reset passed.');
})().catch(e=>{console.error(e);process.exitCode=1;});
