const assert=require('node:assert/strict'),fs=require('node:fs');
const {JSDOM}=require('jsdom');
const assets='android/app/src/main/assets/';
const source=name=>fs.readFileSync(assets+name,'utf8');
const dataset=name=>JSON.parse(source(name));
const dom=new JSDOM('<meta name="theme-color"><main></main>',{url:'https://appassets.androidplatform.net/',runScripts:'outside-only'});
const W=dom.window;
W.CDM={icon:()=>'',empty:()=>''};
for(const name of ['appearance.js','rfaf_extract.js','fixtures.js'])W.eval(source(name));
const f=W.Fixtures,first=dataset('fixtures.json'),filial=dataset('fixtures-filial.json');
const pending=[];
W.fetch=url=>new Promise(resolve=>pending.push({url,reply:data=>resolve({ok:true,json:async()=>data})}));
(async()=>{
 assert.equal(W.Appearance.mode,'dark');
 W.document.body.insertAdjacentHTML('afterbegin',W.Appearance.button());
 W.document.querySelector('[data-theme-toggle]').click();
 assert.equal(W.document.documentElement.dataset.theme,'light');
 assert.equal(W.localStorage.getItem('cdm-theme'),'light');
 assert.equal(W.document.querySelector('[data-theme-toggle]').getAttribute('aria-label'),'Activar modo oscuro');
 W.eval(source('appearance.js'));
 assert.equal(W.Appearance.mode,'light','Theme survives a new bootstrap');
 const writes=[];
 W.AppAppearance={getTheme:()=> 'dark',getTeam:()=> 'filial',setTheme:v=>writes.push(['theme',v]),setTeam:v=>writes.push(['team',v])};
 assert.equal(W.Appearance.stored('theme','light'),'dark','Native preferences work with DOM storage disabled');
 W.Appearance.apply('light',true);W.Appearance.save('team','first');
 assert.deepEqual(writes,[['theme','light'],['team','first']]);
 delete W.AppAppearance;

 const oldCalendar=f.loadFixtures();
 assert.equal(pending[0].url,'fixtures.json');
 f.selectTeam('filial');const newCalendar=f.loadFixtures();
 pending[1].reply(filial);await newCalendar;
 pending[0].reply(first);await oldCalendar;
 assert.equal(f.data.team_key,'filial','An old request cannot replace the selected team');
 assert.equal(f.data.round_matches.filter(m=>m.round===1).length,4);
 f.round='3';f.manualRound=true;
 f.selectTeam('first');const loadFirst=f.loadFixtures();pending[2].reply(first);await loadFirst;
 f.round='5';f.manualRound=true;
 f.selectTeam('filial');assert.equal(f.round,'3');assert.equal(f.data.group,'Grupo A');
 f.selectTeam('first');assert.equal(f.round,'5');assert.match(f.actaHref('2645766'),/equipo=first$/);

 const oldReport=f.loadReport('2645766');
 f.selectTeam('filial');const newReport=f.loadReport('2718118');
 pending[4].reply(dataset('actas/2718118.json'));await newReport;
 const players=JSON.stringify(f.reportData.players);
 pending[3].reply(dataset('actas/2645766.json'));await oldReport;
 assert.equal(f.reportData.id,'2718118');
 assert.equal(JSON.stringify(f.reportData.players),players,'A late acta cannot alter the current player context');
 assert.match(f.playerHref(f.reportData.players[0].id,'2718118'),/equipo=filial$/);
 assert.equal(filial.roster.length,9);
 assert(filial.roster.every(p=>p.id&&p.acta_id&&p.photo));
 assert(filial.standings.every(r=>fs.existsSync(assets+filial.crest_assets[r.crest])),'Every filial crest is bundled');
 dom.window.close();
 console.log('Theme persistence, native preferences, independent team rounds and late calendar/acta responses passed');
})().catch(error=>{console.error(error);dom.window.close();process.exitCode=1;});
