const assert=require('node:assert/strict'),fs=require('node:fs'),{JSDOM}=require('jsdom');
const dom=new JSDOM('<body><header id="header"></header><div id="teams"></div><div id="banner"></div><div id="tabs"></div><main id="main"></main><nav id="nav"></nav></body>',{runScripts:'outside-only',url:'https://club.test/'}),w=dom.window;
w.CDM={icon:()=>'',empty:()=>''};w.eval(fs.readFileSync('server/static/rfaf_extract.js','utf8'));w.eval(fs.readFileSync('server/static/fixtures.js','utf8'));w.eval(fs.readFileSync('server/static/matchday.js','utf8'));
const f=w.Fixtures,c=w.ClubMatchdays,r=w.ClubRefresh;
const game=(round,date,played=false)=>({round,date,played,home:'Nombre largo del local',away:'Visitante',time:'12:00',home_score:2,away_score:1});
const data={matches:[game(1,'2026-10-01',true),game(2,'2026-10-11'),game(3,'2026-10-25')],round_matches:[game(1,'2026-10-01',true),game(2,'2026-10-11'),game(2,'2026-10-12'),game(3,'2026-10-25')]};
assert.equal(c.round(data,'2026-10-09'),'2');assert.equal(c.round(data,'2026-10-12'),'3');assert.equal(c.round({matches:[game(1,'2026-10-01',true)]},'2026-10-09'),'1');
f.teams={first:{label:'Primer Equipo',filename:'fixtures.json'},rfaf_10_20:{label:'Cadete',filename:'fixtures-rfaf_10_20.json'}};f.selectedTeam='first';f.data=data;
c.snapshots={first:data,rfaf_10_20:data};
const actualRound=c.round.bind(c);c.round=data=>actualRound(data,'2026-10-09');const html=c.screen();assert.equal((html.match(/class="matchday-carousel"/g)||[]).length,1);assert.equal((html.match(/class="matchday-card"/g)||[]).length,2);assert(html.includes('Cadete'));assert(html.includes('12:00'));assert(!html.includes('LIGA RIVAL'));const bye={matches:[game(3,'2026-10-25')],round_matches:[game(2,'2026-10-11'),game(3,'2026-10-25')]};assert.equal(c.round(bye,'2026-10-09'),'3','A club bye must not show a rival match');
assert(c.card({...game(2,'2026-10-11',true),acta_url:'https://www.rfaf.es/pnfg/NPcd/NFG_CmpPartido?CodActa=123'},'rfaf_10_20').includes('#acta=123&amp;equipo=rfaf_10_20'));
assert(!c.card({...game(2,'2026-10-11'),acta_url:'https://evil.test/?CodActa=123'},'first').includes('Ver acta'));
w.Appearance={button:()=>''};w.eval(fs.readFileSync('server/static/ui.js','utf8'));w.CDM.shell('Inicio',null);const header=w.document.querySelector('.club-header-brand').innerHTML;f.selectedTeam='rfaf_10_20';w.CDM.shell('Inicio',null);assert.equal(w.document.querySelector('.club-header-brand').innerHTML,header,'Header PNGs stay fixed across categories');const style=w.document.createElement('style');style.textContent=fs.readFileSync('server/static/theme.css','utf8');w.document.head.append(style);for(const theme of ['light','dark']){w.document.documentElement.dataset.theme=theme;assert.equal(w.getComputedStyle(w.document.querySelector('.club-header-'+theme)).display,'block');assert.equal(w.getComputedStyle(w.document.querySelector('.club-header-'+(theme==='light'?'dark':'light'))).display,'none');}for(const theme of ['light','dark'])assert(fs.readFileSync('server/static/club-header-'+theme+'.png').equals(fs.readFileSync('android/app/src/main/assets/club-header-'+theme+'.png')));
const target=w.document.querySelector('main');let refreshed=0;w.refreshScreen=async()=>{refreshed++};
function touch(type,x,y){const event=new w.Event(type,{bubbles:true,cancelable:true});Object.defineProperty(event,'touches',{value:type==='touchend'?[]:[{clientX:x,clientY:y}]});target.dispatchEvent(event);return event;}
(async()=>{touch('touchstart',10,10);touch('touchmove',100,30);touch('touchend',100,30);assert.equal(refreshed,0);touch('touchstart',10,10);touch('touchmove',10,50);touch('touchend',10,50);assert.equal(refreshed,0);touch('touchstart',10,10);assert(touch('touchmove',10,110).defaultPrevented);touch('touchend',10,110);await new Promise(resolve=>setTimeout(resolve,0));assert.equal(refreshed,1);await Promise.all([r.run(),r.run()]);assert.equal(refreshed,2);console.log('Category rounds, all rivals, safe acta navigation, horizontal gesture and refresh threshold verified');dom.window.close();})().catch(e=>{console.error(e);process.exitCode=1});
