plugins { id 'com.android.application' }
android {
    namespace 'es.cdmenciana.app'
    compileSdk 35
    buildToolsVersion '35.0.0'
    defaultConfig {
        applicationId 'es.cdmenciana.app'
        minSdk 26
        targetSdk 35
        versionCode 30
        versionName '0.19.1'
    }
    compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
}
dependencies { testImplementation 'junit:junit:4.13.2' }
