plugins { id 'com.android.application' }
android {
    namespace 'es.cdmenciana.app'
    compileSdk 35
    defaultConfig {
        applicationId 'es.cdmenciana.app'
        minSdk 26
        targetSdk 35
        versionCode 5
        versionName '0.5.0'
    }
    compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
}
